name: abetterworld
favicon: null
layout_spectrum: 0.09099541418254375
typography_spectrum: 0.6101905545219779
title: A Better World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#624e35'
    - '#8eb0b1'
    - '#d99d61'
    - '#fedc9b'
  brandStrength: 0.6374218326527625
  lightness: 0.8622615649364889
  saturation: 0.7035321064759046
  rhythmicContrast: 0.7339908485300839
purpose: []
