name: abetterworld
favicon: null
layout_spectrum: 0.09099541418254375
typography_spectrum: 0.6101905545219779
title: A Better World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6374218326527625
  lightness: 0.8622615649364889
  saturation: 0.7035321064759046
  rhythmicContrast: 0.7339908485300839
purpose: []
